example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here

from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name = 'show_katalog')
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('html/', show_watchlist, name='show_watchlist')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from requests import delete
from todolist.views import (
    register_user,
    login_user,
    logout_user,
    show_todolist,
    create_task,
    delete_task,
    update_task,
    show_json,
    delete_task_with_ajax,
    add_task_with_ajax
)

app_name = "todolist"
urlpatterns = [
    path("", show_todolist, name="show_todolist"),
    path("login/", login_user, name="login"),
    path("register/", register_user, name="register"),
    path("create-task/", create_task, name="create_task"),
    path("logout/", logout_user, name="logout"),
    path("delete-task/<str:id>/", delete_task, name="delete_task"),
    path("update-finished/<str:id>/", update_task, name="update_task"),
    path("json/", show_json, name="show_json"),
    path("delete-task-ajax/<str:id>/", delete_task_with_ajax, name = "delete_task_with_ajax"),
    path("add/", add_task_with_ajax, name="add_task_with_ajax"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=255)
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User


# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,blank=True, null=True,)
    date = models.DateField(auto_now=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from gettext import Catalog
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.

def show_katalog(request):
    list_of_katalogs = CatalogItem.objects.all()
    context = {
        'name' : 'Farel Rishad Akasya',
        'student_Id' : '2106631646',
        'list_katalog' : list_of_katalogs
    }
    return render(
        request,
        'katalog.html',
        context
    )

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

data = MyWatchList.objects.all()

# Create your views here.
def show_watchlist(request):
    movies_watched = 0
    movies_count = 0
    for movie in data:
        movies_count +=1
        if movie.watched:
            movies_watched += 1
    watch_prompt = "Wah, kamu masih sedikit menonton!"

    if movies_watched >= movies_count/2:
        watch_prompt = "Selamat, kamu sudah banyak menonton!"

    context = {
        'list_movies': data ,
        'name' : 'Farel Rishad Akasya',
        'student_Id' : '2106631646',
        'watch_prompt' : watch_prompt
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, HttpResponseNotFound
from django.contrib import messages
from todolist.models import Task
from django.urls import reverse
from django.core import serializers
import datetime

# Create your views here.

@login_required(login_url="/todolist/login/")
def show_todolist(request):
    todolist_objects = Task.objects.filter(user=request.user)
    context = {
        "todolist": todolist_objects, 
        "username": request.user.username
        }
    return render(request, "todolist.html", context)

def register_user(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")
            return redirect("todolist:login")
    
    return render(request, "register.html", {"form":form})

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username = username, password = password)

        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie("last_login", str(datetime.datetime.now()))  
            return response
        else:
            messages.info(request, "Username or Password is incorrect!")

    context = {}
    return render(request, "login.html", context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("todolist:login"))
    response.delete_cookie("last_login")
    return response


@login_required(login_url="/todolist/login/")
def create_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))

    return render(request, "create_task.html")

@login_required(login_url="/todolist/login/")
def delete_task(request, id):
    task = Task.objects.get(user = request.user, pk = id)
    task.delete()

    return redirect(
        "todolist:show_todolist"
    )

@login_required(login_url="/todolist/login/")
def delete_task_with_ajax(request, id):
    if request.method == "DELETE":
        task = Task.objects.get(user=request.user, id=id)
        task.delete()

        return HttpResponse(b"DELETED", status=201)
    
    return HttpResponseNotFound()

@login_required(login_url="/todolist/login/")
def update_task(request, id):
    task = Task.objects.get(user = request.user, pk = id)
    task.is_finished = not task.is_finished
    task.save()
    return redirect("todolist:show_todolist")

@login_required(login_url="/todolist/login/")
def show_json(request):
    task = Task.objects.all()
    return HttpResponse(serializers.serialize("json", task))

@login_required(login_url="/todolist/login/")
def add_task_with_ajax(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        task = Task(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
            is_finished = False
        )
        task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p> {{ name }} </p>

  <h5>Student ID: </h5>
  <p> {{ student_Id }} </p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for katalog_item in list_katalog %}
        <tr>
            <th>{{katalog_item.item_name}}</th>
            <th>{{katalog_item.item_price}}</th>
            <th>{{katalog_item.item_stock}}</th>
            <th>{{katalog_item.rating}}</th>
            <th>{{katalog_item.description}}</th>
            <th>{{katalog_item.item_url}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

 
    
    
    

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Assignment 3 PBP</h1>

  <h5>Name: </h5>
  <p> {{ name }} </p>

  <h5>Student ID: </h5>
  <p> {{ student_Id }} </p>

  <p>{{watch_prompt}}</p>

  <table>
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for movies in list_movies %}
        <tr>
            <th>{{movies.watched}}</th>
            <th>{{movies.title}}</th>
            <th>{{movies.rating}}</th>
            <th>{{movies.release_date}}</th>
            <th>{{movies.review}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

 
    
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>Farel</title>
  <script src="https://cdn.tailwindcss.com"></script

  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends "base.html" %}
{% block content %}


<div class="bg-gray-700 flex flex-col min-h-screen justify-center items-center max-w-[100%] md:max-w-[100%] mx-auto gap-5">

<h2 class="text-4xl font-extrabold dark:text-white">Add New Task</h2>
<p class="mb-4 text-lg font-normal text-gray-500 dark:text-gray-400">What would you like to achieve?</p>

<br>


<a  class="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <form method="post">
        {% csrf_token %}
    
        <div class="mb-6">
            <label for="default-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Title</label>
            <input type="text" name="title" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        </div>
    
        <div class="mb-6">
            <label for="large-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Description</label>
            <input type="text" name="description" class="block p-4 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
        </div>
    
    
        <br>
        <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800" type="submit">
            <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
                Create Task
            </span>
          </button>
    </form> 
</a>



</div>

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="login"div>
    
<form method="POST" action="">
{% csrf_token %}
   
    <div class="bg-gray-700 flex flex-col min-h-screen justify-center items-center max-w-[100%] md:max-w-[100%] mx-auto gap-5">
        <form class="space-y-6" action="#">
            <h5 class="text-xl font-medium text-gray-900 dark:text-white">Sign in</h5>
            <div>
                <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Username</label>
                <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required="">
            </div>
            <div>
                <label for="password" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password</label>
                <input type="password" name="password" id="password" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required="">
            </div>
            
            <input type="submit" value="Log In" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"> 
            <div class="text-sm font-medium text-gray-500 dark:text-gray-300">
                Not registered? <a href="{% url 'todolist:register' %}" class="text-blue-700 hover:underline dark:text-blue-500">Create account</a>
            </div>
        </form>
    </div>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account? <a href="{% url 'todolist:register' %}">Create account</a>

</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}  

<div class="bg-gray-700 flex flex-col min-h-screen justify-center items-center max-w-[100%] md:max-w-[100%] mx-auto gap-5">

  <form method="POST">
    {% csrf_token %}
        <form class="space-y-6" action="#">
            <h5 class="text-xl font-medium text-center text-gray-900 dark:text-white">Register Account</h5>
            <div>
                <label for="username" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Username</label>
                <input type="text" name="username" id="username" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required="">
                {% if form.username.errors %}
                <div class="mt-2 text-red-500 text-sm w-full">
                {{ form.username.errors }}
                </div>
                {% endif %}
            </div>

            <div>
                <label for="password1" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password</label>
                <input type="password" name="password1"  placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required="">
                {% if form.password1.errors %}
                <div class="mt-2 text-red-500 text-sm w-full">
                {{ form.password1.errors }}
                </div>
                {% endif %}
            </div>

            <div>
                <label for="password2" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Password Confirmation</label>
                <input type="password" name="password2" placeholder="••••••••" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white" required="">
                {% if form.password2.errors %}
                <div class="mt-2 text-red-500 text-sm w-full">
                {{ form.password2.errors }}
                </div>
                {% endif %}
            </div>
            <br>
            <input type="submit" value="Register" class="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"> 
            
        </form>
    </div>


  </form>
  <p>
    Have an Account?
    <a
      href="{% url 'todolist:login' %}"
      class="font-bold text-blue-600 underline hover:no-underline"
      >Login</a
    >
  </p>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
{% endblock meta %}

{% block content %}
{% load static %}



<div class="bg-gray-700 flex flex-col min-h-screen justify-center items-center max-w-[100%] md:max-w-[100%] mx-auto gap-5">

  <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
      <a class="flex items-center">
        <img src="https://flowbite.com/docs/images/logo.svg" class="mr-3 h-6 sm:h-9" alt="Flowbite Logo">
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">To Do List</span>
      </a>
    

      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
        <ul class="flex flex-col p-4 mt-4 bg-gray-50 rounded-lg border border-gray-100 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
          <li>
            <a href="#" class="block py-2 pr-4 pl-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white" aria-current="page">Home</a>
          </li>
          <li>
            <a href="{% url 'todolist:logout' %}" class="block py-2 pr-4 pl-3 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Welcome back, {{username}}</h1>


  <br>
  <tbody id="cardcontainer">

  

  </tbody>  
  <br>

  
<!-- Modal toggle -->
<button 
    class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" 
    type="button" 
    data-modal-toggle="authentication-modal"
    id="modal-toggle">
    Create Task

</button>

<!-- Main modal -->
<div
  id="create-task-modal"
  class="w-full fixed flex justify-center w-full z-10 min-h-screen items-center bg-black bg-opacity-50 hidden"
  >

<a  class="block p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
  <div id="close-icon" class="cursor-pointer text-white">
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
      <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </div>
  <form method="post" id="add-task-form">
      {% csrf_token %}
  
      <div class="mb-6">
          <label for="default-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Title</label>
          <input id="title" type="text" name="title" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
      </div>
  
      <div class="mb-6">
          <label for="large-input" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Description</label>
          <input id="description" type="text" name="description" class="block p-4 w-full text-gray-900 bg-gray-50 rounded-lg border border-gray-300 sm:text-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
      </div>
  
  
      <br>
      <button class="relative inline-flex items-center justify-center p-0.5 mb-2 mr-2 overflow-hidden text-sm font-medium text-gray-900 rounded-lg group bg-gradient-to-br from-purple-600 to-blue-500 group-hover:from-purple-600 group-hover:to-blue-500 hover:text-white dark:text-white focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800" type="submit">
          <span class="relative px-5 py-2.5 transition-all ease-in duration-75 bg-white dark:bg-gray-900 rounded-md group-hover:bg-opacity-0">
              Create Task
          </span>
        </button>
  </form> 
</a>

</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

  const openModal = e => {
       
        $("#create-task-modal").removeClass("hidden");
      };

      const closeModal = e => {
        $("#create-task-modal").addClass("hidden");
      };

  

  $(document).ready(function()  {
    refreshTodolist();
    $("#modal-toggle").click(openModal);
    $("#close-icon").click(closeModal);
  });
  
  // async function getTodolist() {
  //   return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
  // }

  function card(item) {
    return `\n
        <tr>
          <div class = "class="card" style="width: 18rem;">
            <div class="p-6 max-w-sm bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
              <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">${item.fields.title}</h5>
              <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">${item.fields.date}</p>
              <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">${item.fields.description}</p>

              <p class="card-text"></p> 
              {% if task.is_finished %}
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Task Finished</p>
              {% else %}
                <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">In Progress</p>
              {% endif %}
            </div>
          </div>
        </tr>
        ` 
  }

  const refreshTodolist = () => {
      // fetching the tasks
      $.get("{% url 'todolist:show_json' %}", data => {
        $.each(data, (i, value) => {
          $("#cardcontainer").append(card(value)); // append to the div
        });
      });
    };

  function add_task_with_ajax() {
    fetch("{% url 'todolist:add_task_with_ajax' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#formtask'))
      }).then(refreshTodolist)
    return false
  }

  $("#add-task-form").submit(e => {
      e.preventDefault();

      // get the CSRF Token
      const csrftoken = document.querySelector(
        "[name=csrfmiddlewaretoken]"
      ).value;

      const title = $("#title").val();
      const description = $("#description").val();

      $.ajax({
        type: "POST",
        url: "{% url 'todolist:add_task_with_ajax' %}",
        headers: { "X-CSRFToken": csrftoken }, // give CSRF token to the header
        mode: "same-origin", // Do not send CSRF token to another domain.
        data: {
          title: title,
          description: description,
        },
        success: response => {
          $("#add-task-form").trigger("reset");
          closeModal();
          $("#cardcontainer").append(card(response));
        },
        error: error => {
          console.log(error);
        },
      });
    });

  document.getElementById("addtaskbutton").onclick = addTodolist
  refreshTodolist()

</script>


{% endblock content %}